blockchains:
  - type: "eth"
    gateway: "EthereumGateway"
    networks:
      - group: "mainnet"
        mode: "main"
        address: "${ETH_MAINNET_ADDR}"
        type: "https"
        token: "${ETHERSCAN_TOKEN}"
      - group: "ropsten"
        mode: "test"
        address: "${ETH_ROPSTEN_ADDR}"
        type: "https"
        token: "${ETHERSCAN_TOKEN}"
  - type: "xrp"
    gateway: "XrpGateway"
    networks:
      - group: "testnet"
        mode: "test"
        address: "https://s.altnet.rippletest.net:51234/"
        type: "json-rpc"
      - group: "devnet"
        mode: "dev"
        address: "https://s.devnet.rippletest.net:51234/"
        type: "json-rpc"
      - group: "mainnet"
        mode: "full-history"
        address: "https://s2.ripple.com:51234/"
        type: "json-rpc"
      - group: "mainnet"
        mode: "public"
        address: "https://s1.ripple.com:51234/"
        type: "json-rpc"
spring:
  jackson:
    deserialization:
      READ_ENUMS_USING_TO_STRING: true
    serialization:
      WRITE_ENUMS_USING_TO_STRING: true

server:
  error:
    include-message: always
